# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
#  About: /about
  Tags: /tags
#  Categories: /categories
#  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname:

# Google Analytics Tracking ID
#google_analytics:

# Social Accounts
#twitter_url: https://twitter.com/?lang=en
#facebook_url: https://www.facebook.com/
#instagram_url: https://www.instagram.com/
#dribble_url: https://dribbble.com/
github_url: https://github.com/awkwardss
#googleplus_url:
#behance_url: https://www.behance.net/
#fivehundredpx_url: https://500px.com/
email_url: chunfengdouruaimi@gmail.com
#rss_url: \#

# Footer About Text
footer_about: "Talk is cheap.<br> Show me the code."

# Footer Copyright Line
footer_copyright: "@Awkwardss-ss. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

